#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

app_path="$0"

while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

app_base_name=${0##*/}
exec_dir=$(cd "$(dirname "$0")" && pwd -P) || exit

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

if [ -z "$JAVA_HOME" ] ; then
    JAVA_HOME=$( dirname "$( which java )" )
    JAVA_HOME=$( cd "$JAVA_HOME/.." && pwd )
fi

if ! [ -x "$JAVA_HOME/bin/java" ] ; then
    die "JAVA_HOME is not defined correctly; can't execute $JAVA_HOME/bin/java"
fi

exec "$JAVA_HOME/bin/java" \
  -Xmx64m \
  -Xms64m \
  -Dorg.gradle.appname=gradlew \
  -cp "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
